GalleryBundle\Entity\Album:
    type: entity
    table: album
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
    oneToMany:
        images:
            targetEntity: Image
            mappedBy: albums