GalleryBundle\Entity\Album:
    type: entity
    table: album
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
#    manyToMany:
#        images:
#            targetEntity: Image
#            joinTable:
#                name: album_has_image
#                joinColumns:
#                    album_id:
#                        referencedColumnName: id
#                inverseJoinColumns:
#                    image_id:
#                        referencedColumnName: id