GalleryBundle\Entity\Image:
    type: entity
    table: image
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        image:
            type: string
            length: 255
            unique: true
    manyToMany:
        album:
            targetEntity: Album
            joinTable:
                name: image_has_album
                joinColumns:
                    image_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    album_id:
                        referencedColumnName: id